
PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

# TODO: port the perl tests in tools/regression/geom_gpt
ATF_TESTS_SH+=	misc
TEST_METADATA+=	execenv="host"

.include <bsd.test.mk>
